version: '2.1'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
    mysql: 
        image: mysql:5.7.27
        environment:
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            # mounting local folder to container -> allows MySQL constainer to read the local files
            # For security reason, MySQL server limits any data load from external files
            # Either place the files into the directory specified by 'scurity-file-priv'
            # or disable the option by passing "" to 'scurity-file-priv' in in mysql.cnf 
            - ./store_files:/store_files_mysql/   
            - ./mysql.cnf:/etc/mysql/mysql.cnf
    webserver:
        image: puckel/docker-airflow:1.10.4
        restart: always
        depends_on:
            - postgres
            - mysql
        environment:
            - INSTALL_MYSQL=y
            - LOAD_EX=n
            - EXECUTOR=Local
            - AIRFLOW__SMTP__SMTP_HOST=smtp.gmail.com
            - AIRFLOW__SMTP__SMTP_USER=minkyung.kang32@gmail.com
            - AIRFLOW__SMTP__SMTP_PASSWORD=hdwiondmyyobhlto
            - AIRFLOW__SMTP__SMTP_PORT=587
            - AIRFLOW__SMTP__SMTP_MAIL_FROM=Airflow
        volumes:
            - ./dags:/usr/local/airflow/dags
            # need to mount the same store_files directory because MySQL and Airflow run on different containers
            - ./store_files:/usr/local/airflow/store_files_airflow
            - ./sql_files:/usr/local/airflow/sql_files
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
